<?php

namespace ContainerG1waJg8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7lBxNsPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7lBxNsP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7lBxNsP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'article' => ['privates', '.errored..service_locator.7lBxNsP.App\\Entity\\article\\Article', NULL, 'Cannot autowire service ".service_locator.7lBxNsP": it needs an instance of "App\\Entity\\article\\Article" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'article' => 'App\\Entity\\article\\Article',
            'em' => '?',
        ]);
    }
}
