<?php

namespace ContainerG1waJg8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IxHm4pNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IxHm4pN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IxHm4pN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\article\\ArticleController::index' => ['privates', '.service_locator.gWmDn6_.App\\Controller\\article\\ArticleController::index()', 'getArticleControllerindexService', true],
            'App\\Controller\\article\\ArticleController::new' => ['privates', '.service_locator.yKhBSRF.App\\Controller\\article\\ArticleController::new()', 'getArticleControllernewService', true],
            'App\\Controller\\article\\ArticleController::edit' => ['privates', '.service_locator.7lBxNsP.App\\Controller\\article\\ArticleController::edit()', 'getArticleControllereditService', true],
            'App\\Controller\\article\\ArticleController::delete' => ['privates', '.service_locator.7lBxNsP.App\\Controller\\article\\ArticleController::delete()', 'getArticleControllerdeleteService', true],
            'App\\Controller\\article\\ArticleController::statsPrice' => ['privates', '.service_locator.gWmDn6_.App\\Controller\\article\\ArticleController::statsPrice()', 'getArticleControllerstatsPriceService', true],
            'App\\Controller\\article\\ArticleController::statsWeight' => ['privates', '.service_locator.gWmDn6_.App\\Controller\\article\\ArticleController::statsWeight()', 'getArticleControllerstatsWeightService', true],
            'App\\Controller\\article\\ConsultantController::index' => ['privates', '.service_locator.sKa82Y8.App\\Controller\\article\\ConsultantController::index()', 'getConsultantControllerindexService', true],
            'App\\Controller\\article\\OrderController::index' => ['privates', '.service_locator.c_jgJSR.App\\Controller\\article\\OrderController::index()', 'getOrderControllerindexService', true],
            'App\\Controller\\article\\OrderController::new' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\article\\OrderController::new()', 'getOrderControllernewService', true],
            'App\\Controller\\article\\OrderController::edit' => ['privates', '.service_locator.xetPGes.App\\Controller\\article\\OrderController::edit()', 'getOrderControllereditService', true],
            'App\\Controller\\article\\OrderController::delete' => ['privates', '.service_locator.xetPGes.App\\Controller\\article\\OrderController::delete()', 'getOrderControllerdeleteService', true],
            'App\\Controller\\article\\OrderController::statsAmount' => ['privates', '.service_locator.c_jgJSR.App\\Controller\\article\\OrderController::statsAmount()', 'getOrderControllerstatsAmountService', true],
            'App\\Controller\\article\\OrderController::statsFees' => ['privates', '.service_locator.c_jgJSR.App\\Controller\\article\\OrderController::statsFees()', 'getOrderControllerstatsFeesService', true],
            'App\\Controller\\article\\TodoController::index' => ['privates', '.service_locator.bCu41p3.App\\Controller\\article\\TodoController::index()', 'getTodoControllerindexService', true],
            'App\\Controller\\article\\TodoController::new' => ['privates', '.service_locator.aRC716W.App\\Controller\\article\\TodoController::new()', 'getTodoControllernewService', true],
            'App\\Controller\\article\\TodoController::edit' => ['privates', '.service_locator.WHaCx8j.App\\Controller\\article\\TodoController::edit()', 'getTodoControllereditService', true],
            'App\\Controller\\article\\TodoController::delete' => ['privates', '.service_locator.WHaCx8j.App\\Controller\\article\\TodoController::delete()', 'getTodoControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\article\\ArticleController:index' => ['privates', '.service_locator.gWmDn6_.App\\Controller\\article\\ArticleController::index()', 'getArticleControllerindexService', true],
            'App\\Controller\\article\\ArticleController:new' => ['privates', '.service_locator.yKhBSRF.App\\Controller\\article\\ArticleController::new()', 'getArticleControllernewService', true],
            'App\\Controller\\article\\ArticleController:edit' => ['privates', '.service_locator.7lBxNsP.App\\Controller\\article\\ArticleController::edit()', 'getArticleControllereditService', true],
            'App\\Controller\\article\\ArticleController:delete' => ['privates', '.service_locator.7lBxNsP.App\\Controller\\article\\ArticleController::delete()', 'getArticleControllerdeleteService', true],
            'App\\Controller\\article\\ArticleController:statsPrice' => ['privates', '.service_locator.gWmDn6_.App\\Controller\\article\\ArticleController::statsPrice()', 'getArticleControllerstatsPriceService', true],
            'App\\Controller\\article\\ArticleController:statsWeight' => ['privates', '.service_locator.gWmDn6_.App\\Controller\\article\\ArticleController::statsWeight()', 'getArticleControllerstatsWeightService', true],
            'App\\Controller\\article\\ConsultantController:index' => ['privates', '.service_locator.sKa82Y8.App\\Controller\\article\\ConsultantController::index()', 'getConsultantControllerindexService', true],
            'App\\Controller\\article\\OrderController:index' => ['privates', '.service_locator.c_jgJSR.App\\Controller\\article\\OrderController::index()', 'getOrderControllerindexService', true],
            'App\\Controller\\article\\OrderController:new' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\article\\OrderController::new()', 'getOrderControllernewService', true],
            'App\\Controller\\article\\OrderController:edit' => ['privates', '.service_locator.xetPGes.App\\Controller\\article\\OrderController::edit()', 'getOrderControllereditService', true],
            'App\\Controller\\article\\OrderController:delete' => ['privates', '.service_locator.xetPGes.App\\Controller\\article\\OrderController::delete()', 'getOrderControllerdeleteService', true],
            'App\\Controller\\article\\OrderController:statsAmount' => ['privates', '.service_locator.c_jgJSR.App\\Controller\\article\\OrderController::statsAmount()', 'getOrderControllerstatsAmountService', true],
            'App\\Controller\\article\\OrderController:statsFees' => ['privates', '.service_locator.c_jgJSR.App\\Controller\\article\\OrderController::statsFees()', 'getOrderControllerstatsFeesService', true],
            'App\\Controller\\article\\TodoController:index' => ['privates', '.service_locator.bCu41p3.App\\Controller\\article\\TodoController::index()', 'getTodoControllerindexService', true],
            'App\\Controller\\article\\TodoController:new' => ['privates', '.service_locator.aRC716W.App\\Controller\\article\\TodoController::new()', 'getTodoControllernewService', true],
            'App\\Controller\\article\\TodoController:edit' => ['privates', '.service_locator.WHaCx8j.App\\Controller\\article\\TodoController::edit()', 'getTodoControllereditService', true],
            'App\\Controller\\article\\TodoController:delete' => ['privates', '.service_locator.WHaCx8j.App\\Controller\\article\\TodoController::delete()', 'getTodoControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\article\\ArticleController::index' => '?',
            'App\\Controller\\article\\ArticleController::new' => '?',
            'App\\Controller\\article\\ArticleController::edit' => '?',
            'App\\Controller\\article\\ArticleController::delete' => '?',
            'App\\Controller\\article\\ArticleController::statsPrice' => '?',
            'App\\Controller\\article\\ArticleController::statsWeight' => '?',
            'App\\Controller\\article\\ConsultantController::index' => '?',
            'App\\Controller\\article\\OrderController::index' => '?',
            'App\\Controller\\article\\OrderController::new' => '?',
            'App\\Controller\\article\\OrderController::edit' => '?',
            'App\\Controller\\article\\OrderController::delete' => '?',
            'App\\Controller\\article\\OrderController::statsAmount' => '?',
            'App\\Controller\\article\\OrderController::statsFees' => '?',
            'App\\Controller\\article\\TodoController::index' => '?',
            'App\\Controller\\article\\TodoController::new' => '?',
            'App\\Controller\\article\\TodoController::edit' => '?',
            'App\\Controller\\article\\TodoController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\article\\ArticleController:index' => '?',
            'App\\Controller\\article\\ArticleController:new' => '?',
            'App\\Controller\\article\\ArticleController:edit' => '?',
            'App\\Controller\\article\\ArticleController:delete' => '?',
            'App\\Controller\\article\\ArticleController:statsPrice' => '?',
            'App\\Controller\\article\\ArticleController:statsWeight' => '?',
            'App\\Controller\\article\\ConsultantController:index' => '?',
            'App\\Controller\\article\\OrderController:index' => '?',
            'App\\Controller\\article\\OrderController:new' => '?',
            'App\\Controller\\article\\OrderController:edit' => '?',
            'App\\Controller\\article\\OrderController:delete' => '?',
            'App\\Controller\\article\\OrderController:statsAmount' => '?',
            'App\\Controller\\article\\OrderController:statsFees' => '?',
            'App\\Controller\\article\\TodoController:index' => '?',
            'App\\Controller\\article\\TodoController:new' => '?',
            'App\\Controller\\article\\TodoController:edit' => '?',
            'App\\Controller\\article\\TodoController:delete' => '?',
        ]);
    }
}
