<?php

namespace ContainerG1waJg8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleControllerstatsWeightService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gWmDn6_.App\Controller\article\ArticleController::statsWeight()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gWmDn6_.App\\Controller\\article\\ArticleController::statsWeight()'] = ($container->privates['.service_locator.gWmDn6_'] ?? $container->load('get_ServiceLocator_GWmDn6Service'))->withContext('App\\Controller\\article\\ArticleController::statsWeight()', $container);
    }
}
