<?php

namespace ContainerG1waJg8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsultantBotServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\article\ConsultantBotService' shared autowired service.
     *
     * @return \App\Service\article\ConsultantBotService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'article'.\DIRECTORY_SEPARATOR.'ConsultantBotService.php';

        return $container->privates['App\\Service\\article\\ConsultantBotService'] = new \App\Service\article\ConsultantBotService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')));
    }
}
