<?php

namespace ContainerG1waJg8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsultantControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sKa82Y8.App\Controller\article\ConsultantController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sKa82Y8.App\\Controller\\article\\ConsultantController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bot' => ['privates', 'App\\Service\\article\\ConsultantBotService', 'getConsultantBotServiceService', true],
        ], [
            'bot' => 'App\\Service\\article\\ConsultantBotService',
        ]))->withContext('App\\Controller\\article\\ConsultantController::index()', $container);
    }
}
