<?php

namespace ContainerG1waJg8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTodoControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aRC716W.App\Controller\article\TodoController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aRC716W.App\\Controller\\article\\TodoController::new()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\article\\TodoRepository', 'getTodoRepositoryService', true],
        ], [
            'em' => '?',
            'repo' => 'App\\Repository\\article\\TodoRepository',
        ]))->withContext('App\\Controller\\article\\TodoController::new()', $container);
    }
}
