<?php

namespace Container9BxKjdJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Uqhq_CService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uqhq._C' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uqhq._C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bot' => ['privates', '.errored.Jx7gx4k', NULL, 'Cannot determine controller argument for "App\\Controller\\article\\ConsultantController::index()": the $bot argument is type-hinted with the non-existent class or interface: "App\\Service\\ConsultantBotService".'],
        ], [
            'bot' => '?',
        ]);
    }
}
