<?php

namespace Container9BxKjdJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XetPGesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xetPGes' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xetPGes'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'order' => ['privates', '.errored..service_locator.xetPGes.App\\Entity\\article\\Order', NULL, 'Cannot autowire service ".service_locator.xetPGes": it needs an instance of "App\\Entity\\article\\Order" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'order' => 'App\\Entity\\article\\Order',
            'em' => '?',
        ]);
    }
}
