<?php

namespace Container9BxKjdJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Jx7gx4kService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.Jx7gx4k' shared service.
     *
     * @return \App\Service\ConsultantBotService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\article\\ConsultantController::index()": the $bot argument is type-hinted with the non-existent class or interface: "App\\Service\\ConsultantBotService".');
    }
}
