<?php

namespace Container9BxKjdJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7lBxNsP.App\Controller\article\ArticleController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7lBxNsP.App\\Controller\\article\\ArticleController::delete()'] = ($container->privates['.service_locator.7lBxNsP'] ?? $container->load('get_ServiceLocator_7lBxNsPService'))->withContext('App\\Controller\\article\\ArticleController::delete()', $container);
    }
}
