<?php

namespace Container9BxKjdJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllerstatsFeesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c_jgJSR.App\Controller\article\OrderController::statsFees()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c_jgJSR.App\\Controller\\article\\OrderController::statsFees()'] = ($container->privates['.service_locator.c_jgJSR'] ?? $container->load('get_ServiceLocator_CJgJSRService'))->withContext('App\\Controller\\article\\OrderController::statsFees()', $container);
    }
}
