<?php

namespace Container9BxKjdJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTodoControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WHaCx8j.App\Controller\article\TodoController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WHaCx8j.App\\Controller\\article\\TodoController::edit()'] = ($container->privates['.service_locator.WHaCx8j'] ?? $container->load('get_ServiceLocator_WHaCx8jService'))->withContext('App\\Controller\\article\\TodoController::edit()', $container);
    }
}
