<?php

namespace Container9BxKjdJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTodoControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bCu41p3.App\Controller\article\TodoController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bCu41p3.App\\Controller\\article\\TodoController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\article\\TodoRepository', 'getTodoRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\article\\TodoRepository',
        ]))->withContext('App\\Controller\\article\\TodoController::index()', $container);
    }
}
